export type Ticker = {
  symbol: string;
  name: string;
  market: "US" | "KR";
};

// US Top ~200 by market cap (S&P 500 leaders + mega caps)
export const US_TICKERS: Ticker[] = [
  { symbol: "AAPL", name: "Apple" },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "NVDA", name: "NVIDIA" },
  { symbol: "GOOGL", name: "Alphabet (Class A)" },
  { symbol: "GOOG", name: "Alphabet (Class C)" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "META", name: "Meta Platforms" },
  { symbol: "BRK-B", name: "Berkshire Hathaway" },
  { symbol: "TSLA", name: "Tesla" },
  { symbol: "AVGO", name: "Broadcom" },
  { symbol: "LLY", name: "Eli Lilly" },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "V", name: "Visa" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "XOM", name: "ExxonMobil" },
  { symbol: "UNH", name: "UnitedHealth" },
  { symbol: "MA", name: "Mastercard" },
  { symbol: "ORCL", name: "Oracle" },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "COST", name: "Costco" },
  { symbol: "HD", name: "Home Depot" },
  { symbol: "ABBV", name: "AbbVie" },
  { symbol: "BAC", name: "Bank of America" },
  { symbol: "KO", name: "Coca-Cola" },
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "CVX", name: "Chevron" },
  { symbol: "MRK", name: "Merck" },
  { symbol: "AMD", name: "AMD" },
  { symbol: "PEP", name: "PepsiCo" },
  { symbol: "TMO", name: "Thermo Fisher" },
  { symbol: "ADBE", name: "Adobe" },
  { symbol: "LIN", name: "Linde" },
  { symbol: "MCD", name: "McDonald's" },
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "ACN", name: "Accenture" },
  { symbol: "ABT", name: "Abbott" },
  { symbol: "WFC", name: "Wells Fargo" },
  { symbol: "DIS", name: "Disney" },
  { symbol: "TMUS", name: "T-Mobile US" },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "QCOM", name: "Qualcomm" },
  { symbol: "DHR", name: "Danaher" },
  { symbol: "IBM", name: "IBM" },
  { symbol: "PM", name: "Philip Morris" },
  { symbol: "VZ", name: "Verizon" },
  { symbol: "INTU", name: "Intuit" },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "AMGN", name: "Amgen" },
  { symbol: "AXP", name: "American Express" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "CAT", name: "Caterpillar" },
  { symbol: "NOW", name: "ServiceNow" },
  { symbol: "PFE", name: "Pfizer" },
  { symbol: "GS", name: "Goldman Sachs" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "RTX", name: "RTX" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "T", name: "AT&T" },
  { symbol: "BKNG", name: "Booking Holdings" },
  { symbol: "BX", name: "Blackstone" },
  { symbol: "SCHW", name: "Charles Schwab" },
  { symbol: "SPGI", name: "S&P Global" },
  { symbol: "BLK", name: "BlackRock" },
  { symbol: "NEE", name: "NextEra Energy" },
  { symbol: "LOW", name: "Lowe's" },
  { symbol: "HON", name: "Honeywell" },
  { symbol: "ETN", name: "Eaton" },
  { symbol: "SYK", name: "Stryker" },
  { symbol: "PGR", name: "Progressive" },
  { symbol: "C", name: "Citigroup" },
  { symbol: "TJX", name: "TJX Companies" },
  { symbol: "ELV", name: "Elevance Health" },
  { symbol: "BSX", name: "Boston Scientific" },
  { symbol: "VRTX", name: "Vertex Pharma" },
  { symbol: "ADP", name: "ADP" },
  { symbol: "MMC", name: "Marsh & McLennan" },
  { symbol: "BMY", name: "Bristol-Myers Squibb" },
  { symbol: "MDT", name: "Medtronic" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "DE", name: "Deere" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "CB", name: "Chubb" },
  { symbol: "ADI", name: "Analog Devices" },
  { symbol: "PLD", name: "Prologis" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "KLAC", name: "KLA" },
  { symbol: "MELI", name: "MercadoLibre" },
  { symbol: "REGN", name: "Regeneron" },
  { symbol: "INTC", name: "Intel" },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "SBUX", name: "Starbucks" },
  { symbol: "CMCSA", name: "Comcast" },
  { symbol: "ANET", name: "Arista Networks" },
  { symbol: "MO", name: "Altria" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "CI", name: "Cigna" },
  { symbol: "TGT", name: "Target" },
  { symbol: "AMT", name: "American Tower" },
  { symbol: "FI", name: "Fiserv" },
  { symbol: "BA", name: "Boeing" },
  { symbol: "EQIX", name: "Equinix" },
  { symbol: "SO", name: "Southern Company" },
  { symbol: "DUK", name: "Duke Energy" },
  { symbol: "ZTS", name: "Zoetis" },
  { symbol: "ICE", name: "Intercontinental Exchange" },
  { symbol: "WM", name: "Waste Management" },
  { symbol: "CME", name: "CME Group" },
  { symbol: "SHW", name: "Sherwin-Williams" },
  { symbol: "CL", name: "Colgate-Palmolive" },
  { symbol: "MCO", name: "Moody's" },
  { symbol: "GD", name: "General Dynamics" },
  { symbol: "EOG", name: "EOG Resources" },
  { symbol: "ITW", name: "Illinois Tool Works" },
  { symbol: "FCX", name: "Freeport-McMoRan" },
  { symbol: "PH", name: "Parker Hannifin" },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "MAR", name: "Marriott" },
  { symbol: "PNC", name: "PNC Financial" },
  { symbol: "NOC", name: "Northrop Grumman" },
  { symbol: "TDG", name: "TransDigm" },
  { symbol: "MMM", name: "3M" },
  { symbol: "CSX", name: "CSX" },
  { symbol: "EMR", name: "Emerson Electric" },
  { symbol: "AON", name: "Aon" },
  { symbol: "WELL", name: "Welltower" },
  { symbol: "COF", name: "Capital One" },
  { symbol: "MCK", name: "McKesson" },
  { symbol: "GM", name: "General Motors" },
  { symbol: "F", name: "Ford" },
  { symbol: "ORLY", name: "O'Reilly Automotive" },
  { symbol: "APH", name: "Amphenol" },
  { symbol: "SLB", name: "Schlumberger" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "AJG", name: "Arthur J. Gallagher" },
  { symbol: "NSC", name: "Norfolk Southern" },
  { symbol: "FDX", name: "FedEx" },
  { symbol: "PCAR", name: "PACCAR" },
  { symbol: "ROP", name: "Roper Technologies" },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "AFL", name: "Aflac" },
  { symbol: "MSI", name: "Motorola Solutions" },
  { symbol: "CARR", name: "Carrier Global" },
  { symbol: "AZO", name: "AutoZone" },
  { symbol: "ABNB", name: "Airbnb" },
  { symbol: "TFC", name: "Truist" },
  { symbol: "TRV", name: "Travelers" },
  { symbol: "BK", name: "Bank of New York Mellon" },
  { symbol: "HCA", name: "HCA Healthcare" },
  { symbol: "ECL", name: "Ecolab" },
  { symbol: "DLR", name: "Digital Realty" },
  { symbol: "OXY", name: "Occidental Petroleum" },
  { symbol: "MPC", name: "Marathon Petroleum" },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "CPRT", name: "Copart" },
  { symbol: "URI", name: "United Rentals" },
  { symbol: "AEP", name: "American Electric Power" },
  { symbol: "VLO", name: "Valero Energy" },
  { symbol: "SPG", name: "Simon Property" },
  { symbol: "HLT", name: "Hilton" },
  { symbol: "AIG", name: "AIG" },
  { symbol: "FTNT", name: "Fortinet" },
  { symbol: "CRWD", name: "CrowdStrike" },
  { symbol: "DDOG", name: "Datadog" },
  { symbol: "DELL", name: "Dell" },
  { symbol: "WMB", name: "Williams Companies" },
  { symbol: "KMB", name: "Kimberly-Clark" },
  { symbol: "MET", name: "MetLife" },
  { symbol: "ALL", name: "Allstate" },
  { symbol: "STZ", name: "Constellation Brands" },
  { symbol: "GIS", name: "General Mills" },
  { symbol: "PRU", name: "Prudential Financial" },
  { symbol: "KMI", name: "Kinder Morgan" },
  { symbol: "OKE", name: "Oneok" },
  { symbol: "PCG", name: "PG&E" },
  { symbol: "D", name: "Dominion Energy" },
  { symbol: "EXC", name: "Exelon" },
  { symbol: "CTAS", name: "Cintas" },
  { symbol: "FAST", name: "Fastenal" },
  { symbol: "ODFL", name: "Old Dominion Freight" },
  { symbol: "VRSK", name: "Verisk Analytics" },
  { symbol: "PAYX", name: "Paychex" },
  { symbol: "IDXX", name: "IDEXX Laboratories" },
  { symbol: "CDNS", name: "Cadence Design" },
  { symbol: "SNPS", name: "Synopsys" },
  { symbol: "MRVL", name: "Marvell" },
  { symbol: "NXPI", name: "NXP Semiconductors" },
  { symbol: "FANG", name: "Diamondback Energy" },
  { symbol: "HES", name: "Hess" },
  { symbol: "KHC", name: "Kraft Heinz" },
  { symbol: "MNST", name: "Monster Beverage" },
  { symbol: "ADSK", name: "Autodesk" },
  { symbol: "WDAY", name: "Workday" },
  { symbol: "TEAM", name: "Atlassian" },
  { symbol: "SQ", name: "Block" },
  { symbol: "SHOP", name: "Shopify" },
  { symbol: "COIN", name: "Coinbase" },
  { symbol: "PLTR", name: "Palantir" },
  { symbol: "SNOW", name: "Snowflake" },
  { symbol: "NET", name: "Cloudflare" },
  { symbol: "MDB", name: "MongoDB" },
  { symbol: "ZS", name: "Zscaler" },
].map((t) => ({ ...t, market: "US" as const }));

// Korea KOSPI 200 leading constituents (Yahoo uses .KS suffix)
export const KR_TICKERS: Ticker[] = [
  { symbol: "005930.KS", name: "삼성전자" },
  { symbol: "000660.KS", name: "SK하이닉스" },
  { symbol: "373220.KS", name: "LG에너지솔루션" },
  { symbol: "207940.KS", name: "삼성바이오로직스" },
  { symbol: "005380.KS", name: "현대차" },
  { symbol: "005935.KS", name: "삼성전자우" },
  { symbol: "000270.KS", name: "기아" },
  { symbol: "068270.KS", name: "셀트리온" },
  { symbol: "035420.KS", name: "NAVER" },
  { symbol: "012330.KS", name: "현대모비스" },
  { symbol: "105560.KS", name: "KB금융" },
  { symbol: "055550.KS", name: "신한지주" },
  { symbol: "005490.KS", name: "POSCO홀딩스" },
  { symbol: "035720.KS", name: "카카오" },
  { symbol: "028260.KS", name: "삼성물산" },
  { symbol: "066570.KS", name: "LG전자" },
  { symbol: "051910.KS", name: "LG화학" },
  { symbol: "006400.KS", name: "삼성SDI" },
  { symbol: "086790.KS", name: "하나금융지주" },
  { symbol: "316140.KS", name: "우리금융지주" },
  { symbol: "003670.KS", name: "포스코퓨처엠" },
  { symbol: "015760.KS", name: "한국전력" },
  { symbol: "017670.KS", name: "SK텔레콤" },
  { symbol: "032830.KS", name: "삼성생명" },
  { symbol: "033780.KS", name: "KT&G" },
  { symbol: "030200.KS", name: "KT" },
  { symbol: "034730.KS", name: "SK" },
  { symbol: "009150.KS", name: "삼성전기" },
  { symbol: "010130.KS", name: "고려아연" },
  { symbol: "011200.KS", name: "HMM" },
  { symbol: "018260.KS", name: "삼성에스디에스" },
  { symbol: "010950.KS", name: "S-Oil" },
  { symbol: "267260.KS", name: "HD현대일렉트릭" },
  { symbol: "267250.KS", name: "HD현대" },
  { symbol: "329180.KS", name: "HD현대중공업" },
  { symbol: "010140.KS", name: "삼성중공업" },
  { symbol: "047810.KS", name: "한국항공우주" },
  { symbol: "064350.KS", name: "현대로템" },
  { symbol: "012450.KS", name: "한화에어로스페이스" },
  { symbol: "009540.KS", name: "HD한국조선해양" },
  { symbol: "402340.KS", name: "SK스퀘어" },
  { symbol: "352820.KS", name: "하이브" },
  { symbol: "041510.KS", name: "에스엠" },
  { symbol: "035900.KQ", name: "JYP Ent." },
  { symbol: "122870.KS", name: "와이지엔터테인먼트" },
  { symbol: "251270.KS", name: "넷마블" },
  { symbol: "036570.KS", name: "엔씨소프트" },
  { symbol: "112040.KQ", name: "위메이드" },
  { symbol: "293490.KS", name: "카카오게임즈" },
  { symbol: "041960.KS", name: "코미팜" },
  { symbol: "326030.KS", name: "SK바이오팜" },
  { symbol: "302440.KS", name: "SK바이오사이언스" },
  { symbol: "196170.KQ", name: "알테오젠" },
  { symbol: "091990.KQ", name: "셀트리온헬스케어" },
  { symbol: "145020.KS", name: "휴젤" },
  { symbol: "069620.KS", name: "대웅제약" },
  { symbol: "128940.KS", name: "한미약품" },
  { symbol: "000100.KS", name: "유한양행" },
  { symbol: "009830.KS", name: "한화솔루션" },
  { symbol: "011170.KS", name: "롯데케미칼" },
  { symbol: "078930.KS", name: "GS" },
  { symbol: "096770.KS", name: "SK이노베이션" },
  { symbol: "001040.KS", name: "CJ" },
  { symbol: "097950.KS", name: "CJ제일제당" },
  { symbol: "035250.KS", name: "강원랜드" },
  { symbol: "008770.KS", name: "호텔신라" },
  { symbol: "271560.KS", name: "오리온" },
  { symbol: "271940.KS", name: "일진하이솔루스" },
  { symbol: "139480.KS", name: "이마트" },
  { symbol: "069960.KS", name: "현대백화점" },
  { symbol: "004170.KS", name: "신세계" },
  { symbol: "023530.KS", name: "롯데쇼핑" },
  { symbol: "071050.KS", name: "한국금융지주" },
  { symbol: "138930.KS", name: "BNK금융지주" },
  { symbol: "175330.KS", name: "JB금융지주" },
  { symbol: "024110.KS", name: "기업은행" },
  { symbol: "088980.KS", name: "맥쿼리인프라" },
  { symbol: "086280.KS", name: "현대글로비스" },
  { symbol: "180640.KS", name: "한진칼" },
  { symbol: "003490.KS", name: "대한항공" },
  { symbol: "020560.KS", name: "아시아나항공" },
  { symbol: "047050.KS", name: "포스코인터내셔널" },
  { symbol: "010620.KS", name: "현대미포조선" },
  { symbol: "042660.KS", name: "한화오션" },
  { symbol: "079550.KS", name: "LIG넥스원" },
  { symbol: "272210.KS", name: "한화시스템" },
  { symbol: "272450.KS", name: "진에어" },
  { symbol: "298050.KS", name: "효성첨단소재" },
  { symbol: "298040.KS", name: "효성중공업" },
  { symbol: "004020.KS", name: "현대제철" },
  { symbol: "005380.KS", name: "현대차" },
  { symbol: "003550.KS", name: "LG" },
  { symbol: "001120.KS", name: "LX인터내셔널" },
  { symbol: "383220.KS", name: "F&F" },
  { symbol: "111770.KS", name: "영원무역" },
  { symbol: "161890.KS", name: "한국콜마" },
  { symbol: "090430.KS", name: "아모레퍼시픽" },
  { symbol: "051900.KS", name: "LG생활건강" },
  { symbol: "002790.KS", name: "아모레G" },
  { symbol: "005850.KS", name: "에스엘" },
  { symbol: "108860.KS", name: "셀바스AI" },
  { symbol: "192820.KS", name: "코스맥스" },
  { symbol: "214150.KS", name: "클래시스" },
  { symbol: "067160.KQ", name: "아프리카TV" },
  { symbol: "263750.KQ", name: "펄어비스" },
  { symbol: "095660.KQ", name: "네오위즈" },
  { symbol: "194480.KQ", name: "데브시스터즈" },
  { symbol: "078340.KQ", name: "컴투스" },
  { symbol: "194370.KS", name: "제이에스코퍼레이션" },
  { symbol: "005830.KS", name: "DB손해보험" },
  { symbol: "000810.KS", name: "삼성화재" },
  { symbol: "082640.KS", name: "동양생명" },
  { symbol: "088350.KS", name: "한화생명" },
  { symbol: "001450.KS", name: "현대해상" },
  { symbol: "032640.KS", name: "LG유플러스" },
  { symbol: "036460.KS", name: "한국가스공사" },
  { symbol: "267290.KS", name: "경동도시가스" },
  { symbol: "005440.KS", name: "현대지에프홀딩스" },
  { symbol: "021240.KS", name: "코웨이" },
  { symbol: "111770.KS", name: "영원무역" },
  { symbol: "001740.KS", name: "SK네트웍스" },
  { symbol: "010620.KS", name: "현대미포조선" },
  { symbol: "047040.KS", name: "대우건설" },
  { symbol: "375500.KS", name: "DL이앤씨" },
  { symbol: "000720.KS", name: "현대건설" },
  { symbol: "006360.KS", name: "GS건설" },
  { symbol: "028050.KS", name: "삼성E&A" },
  { symbol: "010060.KS", name: "OCI홀딩스" },
  { symbol: "456040.KS", name: "OCI" },
  { symbol: "120110.KS", name: "코오롱인더" },
  { symbol: "271980.KS", name: "제일약품" },
  { symbol: "298690.KS", name: "에어부산" },
  { symbol: "003410.KS", name: "쌍용C&E" },
  { symbol: "000990.KS", name: "DB하이텍" },
  { symbol: "042700.KS", name: "한미반도체" },
  { symbol: "240810.KS", name: "원익IPS" },
  { symbol: "036930.KS", name: "주성엔지니어링" },
  { symbol: "058470.KQ", name: "리노공업" },
  { symbol: "095340.KQ", name: "ISC" },
  { symbol: "036490.KQ", name: "SK머티리얼즈" },
  { symbol: "081000.KS", name: "삼양사" },
  { symbol: "145720.KS", name: "덴티움" },
  { symbol: "131370.KS", name: "알에프텍" },
  { symbol: "099190.KS", name: "아이센스" },
  { symbol: "950140.KS", name: "잉글우드랩" },
  { symbol: "950130.KS", name: "엑세스바이오" },
  { symbol: "950170.KS", name: "JTC" },
  { symbol: "234080.KQ", name: "JW생명과학" },
  { symbol: "048410.KQ", name: "현대바이오" },
  { symbol: "950210.KS", name: "프레스티지바이오파마" },
  { symbol: "247540.KQ", name: "에코프로비엠" },
  { symbol: "086520.KQ", name: "에코프로" },
  { symbol: "066970.KQ", name: "엘앤에프" },
  { symbol: "121600.KQ", name: "나노신소재" },
  { symbol: "418550.KQ", name: "제이오" },
  { symbol: "058610.KQ", name: "에스피지" },
  { symbol: "108320.KQ", name: "실리콘웍스" },
  { symbol: "357780.KQ", name: "솔브레인" },
  { symbol: "095610.KQ", name: "테스" },
  { symbol: "067310.KQ", name: "하나마이크론" },
  { symbol: "115160.KQ", name: "휴맥스홀딩스" },
  { symbol: "041960.KQ", name: "코미팜" },
  { symbol: "078160.KQ", name: "메디포스트" },
  { symbol: "298380.KQ", name: "에이비엘바이오" },
  { symbol: "086900.KQ", name: "메디톡스" },
  { symbol: "950160.KQ", name: "코오롱티슈진" },
  { symbol: "237690.KQ", name: "에스티팜" },
  { symbol: "950220.KQ", name: "네오이뮨텍" },
  { symbol: "950110.KQ", name: "SBI핀테크솔루션즈" },
  { symbol: "950200.KS", name: "소마젠" },
  { symbol: "166090.KS", name: "하나머티리얼즈" },
  { symbol: "950190.KQ", name: "미투젠" },
  { symbol: "950180.KQ", name: "SNK" },
  { symbol: "035600.KQ", name: "KG이니시스" },
  { symbol: "060280.KQ", name: "큐렉소" },
  { symbol: "071970.KS", name: "HD현대마린엔진" },
  { symbol: "402420.KS", name: "노바렉스" },
  { symbol: "377300.KS", name: "카카오페이" },
  { symbol: "377190.KS", name: "더블유씨피" },
  { symbol: "281820.KS", name: "케이씨텍" },
  { symbol: "036540.KQ", name: "SFA반도체" },
  { symbol: "950140.KQ", name: "잉글우드랩" },
  { symbol: "036570.KQ", name: "엔씨소프트" },
].map((t) => ({ ...t, market: "KR" as const }));

// Dedupe by symbol just in case
const seen = new Set<string>();
export const ALL_TICKERS: Ticker[] = [...US_TICKERS, ...KR_TICKERS].filter((t) => {
  if (seen.has(t.symbol)) return false;
  seen.add(t.symbol);
  return true;
});
